### PR TITLE
Form validation

### PR DESCRIPTION
**Pull request by davidread**
It still uses sqlite, so postgres would be preferable.

Some more care might be done over the error display to match: https://govuk-elements.herokuapp.com/errors/

### CODE REVIEW

**Comment by andreagrandi** [comment]
@davidread I would mark this as [WIP] until we don't add support for PostgreSQL, because as far as I know each request you make isn't guaranteed to even run in the same process, when you run in a PAAS/Heroku, this means that the tables created during the initial deployment/migration, won't exist by the time you make the first request because the sqlite file won't be there anymore

**Comment by davidread** [comment]
Ok I disabled the saving for now. Merging this will give us the form validation.

**Comment by andreagrandi** [comment]
Isn't the form currently being validated? https://github.com/alphagov/sandbox-mgt/blob/master/sandboxmgt/app/views.py#L15
Or are you talking about a different validation?

**Comment by davidread** [comment]
The text boxes are currently validated, but with no user feedback. I also added validation for the checkbox.

**Review by andreagrandi — APPROVED** [review]

**Pull request merged**
